version: '3'

services:
  database:
    image: postgres
    volumes:
      - ./volume.sql:/docker-entrypoint-initdb.d/volume.sql
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"