DROP TABLE public.account CASCADE;

DROP TABLE public.bus CASCADE;

DROP TABLE public.city CASCADE;

DROP TABLE public.company CASCADE;

DROP TABLE public.company_type CASCADE;

DROP TABLE public.customer CASCADE;

DROP TABLE public.permission_level CASCADE;

DROP TABLE public.person CASCADE;

DROP TABLE public.ticket CASCADE;

DROP TABLE public.ticket_status CASCADE;

DROP TABLE public.travel CASCADE;


CREATE TABLE "person" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "permission_level" smallint NOT NULL,
  "customer_id" integer UNIQUE,
  "company_id" integer UNIQUE,
  "city_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "cpf" bigint UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "phone" numeric,
  "birth_date" date,
  "company_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "company" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "cnpj" bigint UNIQUE NOT NULL,
  "social_reason" varchar UNIQUE NOT NULL,
  "fantasy_name" varchar,
  "phone" numeric,
  "company_type_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "company_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "person_id" integer UNIQUE NOT NULL,
  "last_access" date NOT NULL,
  "tickets_left" smallint,
  "daily_tickets" smallint NOT NULL,
  "created_at" date NOT NULL,
  "updated_at" date
);

CREATE TABLE "bus" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" numeric NOT NULL,
  "max_passengers" smallint,
  "account_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "ticket" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "account_id" integer NOT NULL,
  "status_id" integer NOT NULL,
  "travel_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "ticket_status" (
  "id" integer PRIMARY KEY,
  "description" varchar NOT NULL
);

CREATE TABLE "travel" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price" float NOT NULL,
  "account_id" integer NOT NULL,
  "bus_id" integer NOT NULL,
  "status" integer NOT NULL,
  "departure_time" timestamp NOT NULL,
  "departure_city_id" integer NOT NULL,
  "arrival_time" timestamp NOT NULL,
  "arrival_city_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "city" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "permission_level" (
  "id" integer UNIQUE PRIMARY KEY,
  "description" varchar NOT NULL
);

ALTER TABLE "travel" ADD FOREIGN KEY ("bus_id") REFERENCES "bus" ("id");

ALTER TABLE "travel" ADD FOREIGN KEY ("departure_city_id") REFERENCES "city" ("id");

ALTER TABLE "travel" ADD FOREIGN KEY ("arrival_city_id") REFERENCES "city" ("id");

ALTER TABLE "account" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("id");

ALTER TABLE "person" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "person" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

ALTER TABLE "company" ADD FOREIGN KEY ("company_type_id") REFERENCES "company_type" ("id");

ALTER TABLE "person" ADD FOREIGN KEY ("permission_level") REFERENCES "permission_level" ("id");

ALTER TABLE "travel" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "ticket" ADD FOREIGN KEY ("status_id") REFERENCES "ticket_status" ("id");

ALTER TABLE "ticket" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "customer" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "person" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "bus" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");